---
abstract: 'Traverse a directory tree through Net::FTP'
author:
  - 'Taku Amano <taku@toi-planning.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::FTP::Server: 0
  Test::More: 0.88
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-FTP-Find
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Net::FTP: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/usualoma/p5-net-ftp-find.git
version: 0.011
